# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown

title: Emmanuel DEMEY
description: Spécialiste Web
author:
  name: Emmanuel Demey
  email: demey.emmanuel@gmail.com
  github: Gillespie59
  twitter: Emmanuel DEMEY
  linkedin: emmanueldemey
  bio: Spécialiste Web
  email_md5: 7a15d4add39891269c15f0ce085c8bed

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
